/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.generator;

import com.google.common.base.Objects;
import com.google.common.collect.Iterables;
import com.google.common.collect.Iterators;
import java.util.Arrays;
import java.util.function.Consumer;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.IntegerRange;
import org.xtext.example.mydsl.sensorHub.Arduino;
import org.xtext.example.mydsl.sensorHub.Average;
import org.xtext.example.mydsl.sensorHub.Com;
import org.xtext.example.mydsl.sensorHub.Edge;
import org.xtext.example.mydsl.sensorHub.Fog;
import org.xtext.example.mydsl.sensorHub.Nrf24l01;
import org.xtext.example.mydsl.sensorHub.PreProcessor;
import org.xtext.example.mydsl.sensorHub.RaspPi;
import org.xtext.example.mydsl.sensorHub.Sensor;
import org.xtext.example.mydsl.sensorHub.SensorSystem;
import org.xtext.example.mydsl.sensorHub.Sound;
import org.xtext.example.mydsl.sensorHub.Sr04;
import org.xtext.example.mydsl.sensorHub.Storage;
import org.xtext.example.mydsl.sensorHub.Threshold;
import org.xtext.example.mydsl.sensorHub.Visualizer;
import org.xtext.example.mydsl.sensorHub.Water_level;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class SensorHubGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    final SensorSystem modelInstance = Iterators.<SensorSystem>filter(resource.getAllContents(), SensorSystem.class).next();
    final Consumer<Fog> _function = (Fog it) -> {
      this.generateFogFile(it, fsa);
    };
    Iterables.<Fog>filter(modelInstance.getDevices(), Fog.class).forEach(_function);
    final Consumer<Fog> _function_1 = (Fog it) -> {
      this.generateEdgeFiles(it, fsa);
    };
    Iterables.<Fog>filter(modelInstance.getDevices(), Fog.class).forEach(_function_1);
  }
  
  public void generateEdgeFiles(final Fog fog, final IFileSystemAccess2 fsa) {
    EList<Edge> _edgeDevices = fog.getEdgeDevices();
    for (final Edge e : _edgeDevices) {
      Arduino _device = e.getDevice();
      boolean _matched = false;
      if (_device instanceof Arduino) {
        _matched=true;
        String _name = fog.getName();
        String _plus = ("./" + _name);
        String _plus_1 = (_plus + "/Edges/");
        String _name_1 = e.getName();
        String _plus_2 = (_plus_1 + _name_1);
        String _plus_3 = (_plus_2 + "/");
        String _name_2 = e.getName();
        String _plus_4 = (_plus_3 + _name_2);
        String _plus_5 = (_plus_4 + ".ino");
        fsa.generateFile(_plus_5, this.generateArduino(e, fog.getComs()));
      }
    }
  }
  
  public void generateFogFile(final Fog fog, final IFileSystemAccess2 fsa) {
    RaspPi _device = fog.getDevice();
    boolean _matched = false;
    if (_device instanceof RaspPi) {
      _matched=true;
      String _name = fog.getName();
      String _plus = ("./" + _name);
      String _plus_1 = (_plus + "/");
      String _name_1 = fog.getName();
      String _plus_2 = (_plus_1 + _name_1);
      String _plus_3 = (_plus_2 + ".py");
      fsa.generateFile(_plus_3, this.generateRaspPi(fog));
    }
  }
  
  public CharSequence generateRaspPi(final Fog pi) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("import time");
    _builder.newLine();
    _builder.append("import struct");
    _builder.newLine();
    _builder.append("import board");
    _builder.newLine();
    _builder.append("import digitalio");
    _builder.newLine();
    _builder.newLine();
    _builder.append("#Setup of communication");
    _builder.newLine();
    CharSequence _generatePythonComSetup = this.generatePythonComSetup(pi.getComs(), pi.getEdgeDevices());
    _builder.append(_generatePythonComSetup);
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("#Reciever function");
    _builder.newLine();
    CharSequence _generateReceiverFunction = this.generateReceiverFunction(pi.getComs());
    _builder.append(_generateReceiverFunction);
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.newLine();
    _builder.append("#Edge device storage and viz code: ");
    _builder.newLine();
    _builder.newLine();
    {
      EList<Storage> _storage = pi.getDevice().getStorage();
      for(final Storage s : _storage) {
        {
          String _type = s.getType();
          boolean _equals = Objects.equal(_type, "txt");
          if (_equals) {
            CharSequence _generatePythonStorageTxt = this.generatePythonStorageTxt();
            _builder.append(_generatePythonStorageTxt);
            _builder.newLineIfNotEmpty();
          }
        }
        _builder.newLine();
      }
    }
    {
      EList<Visualizer> _visualization = pi.getDevice().getVisualization();
      for(final Visualizer v : _visualization) {
        {
          String _type_1 = v.getType();
          boolean _equals_1 = Objects.equal(_type_1, "console");
          if (_equals_1) {
            CharSequence _generatePythonVizConsole = this.generatePythonVizConsole();
            _builder.append(_generatePythonVizConsole);
            _builder.newLineIfNotEmpty();
          }
        }
      }
    }
    return _builder;
  }
  
  protected CharSequence _generateReceiverFunction(final Fog f) {
    StringConcatenation _builder = new StringConcatenation();
    return _builder;
  }
  
  protected CharSequence _generateReceiverFunction(final Nrf24l01 nrf) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("def receive(timeout=");
    int _timeout = nrf.getTimeout();
    _builder.append(_timeout);
    _builder.append("):");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("\"\"\"Polls the radio and prints the received value. This method expires");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("after if no transmission is recieved within the timeout\"\"\"");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("# put radio into RX mode and power up");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("nrf.listen = True");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("start = time.monotonic()");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("while (time.monotonic() - start) < timeout:");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("if nrf.available():");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("# grab information about the received payload");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("payload_size, pipe_number = (nrf.any(), nrf.pipe)");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("# fetch 1 payload from RX FIFO");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("buffer = nrf.read()  # also clears nrf.irq_dr status flag");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("# format string \"<f\"");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("# buffer[:4] truncates padded 0s if dynamic payloads are disabled");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("payload[0] = struct.unpack(\"<f\", buffer[:4])[0]");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("# print details about the received packet");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("timestamp = time.time()");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("save(addresses[pipe_number-1], timestamp, payload[0])");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("visualize(addresses[pipe_number-1], timestamp, payload[0])");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("start = time.monotonic()");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("# recommended behavior is to keep in TX mode while idle");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("nrf.listen = False  # put the nRF24L01 is in TX mode");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generatePythonComSetup(final Com c, final EList<Edge> edges) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("from circuitpython_nrf24l01.rf24 import RF24");
    _builder.newLine();
    _builder.newLine();
    _builder.append("# digital output pins");
    _builder.newLine();
    _builder.append("ce = digitalio.DigitalInOut(board.D4)");
    _builder.newLine();
    _builder.append("csn = digitalio.DigitalInOut(board.D5)");
    _builder.newLine();
    _builder.newLine();
    _builder.append("# init spi bus object");
    _builder.newLine();
    _builder.append("spi = board.SPI()  ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("# initialize the nRF24L01 on the spi bus object");
    _builder.newLine();
    _builder.append("nrf = RF24(spi, csn, ce)");
    _builder.newLine();
    _builder.newLine();
    _builder.append("# set power amplifier level (RF24_PA_MIN, RF24_PA_LOW, RF24_PA_MED, RF24_PA_HIGH)");
    _builder.newLine();
    _builder.append("nrf.pa_level = RF24_PA_LOW");
    _builder.newLine();
    _builder.newLine();
    _builder.append("# addresses needs to be in a buffer protocol object (bytearray)");
    _builder.newLine();
    _builder.append("addresses = [");
    {
      boolean _hasElements = false;
      for(final Edge e : edges) {
        if (!_hasElements) {
          _hasElements = true;
        } else {
          _builder.appendImmediate(",", "");
        }
        _builder.append("b\"");
        String _name = e.getName();
        _builder.append(_name);
        _builder.append("\"");
      }
    }
    _builder.append("]");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("# set RX address of TX node into RX pipes");
    _builder.newLine();
    {
      int _size = edges.size();
      IntegerRange _upTo = new IntegerRange(1, _size);
      for(final Integer i : _upTo) {
        _builder.append("nrf.open_rx_pipe(");
        _builder.append(i);
        _builder.append(", address[");
        _builder.append(i);
        _builder.append("])  # using pipe ");
        _builder.append(i);
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.newLine();
    _builder.append("# list to store float number for the payloads sent");
    _builder.newLine();
    _builder.append("payload = [0.0]");
    _builder.newLine();
    _builder.newLine();
    _builder.append("# for compatibility with TMRh20 library");
    _builder.newLine();
    _builder.append("nrf.allow_ask_no_ack = False");
    _builder.newLine();
    _builder.append("nrf.dynamic_payloads = False");
    _builder.newLine();
    _builder.append("nrf.payload_length = 32");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generatePythonStorageTxt() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("def saveTxt(addr, timestamp, value):");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("with open(\"./\" + str(addr) + \".txt\", \"a\") as f:");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("f.write(str(timestamp) + \", \" + str(value) + \"\\n\")");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generatePythonVizConsole() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("def toConsole(addr, timestamp, value):");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("print(str(addr) + \": \" + str(timestamp) + \", \" + str(value))");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateArduino(final Edge ino, final Com coms) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("//Send.ino");
    _builder.newLine();
    _builder.append("#include<SPI.h>");
    _builder.newLine();
    CharSequence _generateInoComsImports = this.generateInoComsImports(ino, coms);
    _builder.append(_generateInoComsImports);
    _builder.newLineIfNotEmpty();
    {
      EList<Sensor> _sensors = ino.getDevice().getSensors();
      for(final Sensor s : _sensors) {
        CharSequence _generateInoSensorImports = this.generateInoSensorImports(s);
        _builder.append(_generateInoSensorImports);
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.newLine();
    _builder.append("void setup(void){");
    _builder.newLine();
    CharSequence _generateInoComsSetup = this.generateInoComsSetup(coms);
    _builder.append(_generateInoComsSetup);
    _builder.newLineIfNotEmpty();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("void loop(void){");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("int sendTime = millis() + ");
    int _rate = ino.getDevice().getRate();
    _builder.append(_rate, "\t");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    {
      EList<Sensor> _sensors_1 = ino.getDevice().getSensors();
      for(final Sensor s_1 : _sensors_1) {
        _builder.append("\t");
        CharSequence _generateInoSensorVars = this.generateInoSensorVars(s_1, s_1.getPreprocessor());
        _builder.append(_generateInoSensorVars, "\t");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\t");
    _builder.append("while(sendTime >= millis()){");
    _builder.newLine();
    {
      EList<Sensor> _sensors_2 = ino.getDevice().getSensors();
      for(final Sensor s_2 : _sensors_2) {
        {
          PreProcessor _preprocessor = s_2.getPreprocessor();
          if ((_preprocessor instanceof Average)) {
            _builder.append("\t\tif(read");
            String _name = s_2.getName();
            _builder.append(_name);
            _builder.append("(temp");
            String _name_1 = s_2.getName();
            _builder.append(_name_1);
            _builder.append(")){");
            _builder.newLineIfNotEmpty();
            _builder.append("\t\t\t");
            _builder.append("count");
            String _name_2 = s_2.getName();
            _builder.append(_name_2, "\t\t\t");
            _builder.append(" += 1;");
            _builder.newLineIfNotEmpty();
            _builder.append("\t\t");
            _builder.append("}");
            _builder.newLine();
          } else {
            _builder.append("read");
            String _name_3 = s_2.getName();
            _builder.append(_name_3);
            _builder.append("(temp");
            String _name_4 = s_2.getName();
            _builder.append(_name_4);
            _builder.append(");");
            _builder.newLineIfNotEmpty();
          }
        }
      }
    }
    _builder.append("\t\t");
    _builder.append("delay(1);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    {
      EList<Sensor> _sensors_3 = ino.getDevice().getSensors();
      for(final Sensor s_3 : _sensors_3) {
        _builder.append("\t");
        CharSequence _generateInoSensorProc = this.generateInoSensorProc(s_3, s_3.getPreprocessor());
        _builder.append(_generateInoSensorProc, "\t");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("radio.write(final");
        String _name_5 = s_3.getName();
        _builder.append(_name_5, "\t");
        _builder.append(", sizeof(final");
        String _name_6 = s_3.getName();
        _builder.append(_name_6, "\t");
        _builder.append("));");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\t");
    _builder.append("delay(1);");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    {
      EList<Sensor> _sensors_4 = ino.getDevice().getSensors();
      for(final Sensor s_4 : _sensors_4) {
        CharSequence _generateInoSensorRead = this.generateInoSensorRead(s_4);
        _builder.append(_generateInoSensorRead);
        _builder.newLineIfNotEmpty();
      }
    }
    return _builder;
  }
  
  protected CharSequence _generateInoSensorImports(final Sound s) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("int ");
    String _name = s.getName();
    _builder.append(_name);
    _builder.append("AnalogPin = 1;");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _generateInoSensorImports(final Water_level s) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("int ");
    String _name = s.getName();
    _builder.append(_name);
    _builder.append("AnalogPin = 0;");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _generateInoSensorImports(final Sr04 s) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("#include \"SR04.h\"");
    _builder.newLine();
    _builder.newLine();
    _builder.append("#define ");
    String _name = s.getName();
    _builder.append(_name);
    _builder.append("TRIG_PIN 12");
    _builder.newLineIfNotEmpty();
    _builder.append("#define ");
    String _name_1 = s.getName();
    _builder.append(_name_1);
    _builder.append("ECHO_PIN 11");
    _builder.newLineIfNotEmpty();
    _builder.append("SR04 sr04 = SR04(");
    String _name_2 = s.getName();
    _builder.append(_name_2);
    _builder.append("ECHO_PIN, ");
    String _name_3 = s.getName();
    _builder.append(_name_3);
    _builder.append("TRIG_PIN);");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _generateInoSensorProc(final Sensor s, final Threshold th) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("final");
    String _name = s.getName();
    _builder.append(_name);
    _builder.append(" = temp");
    String _name_1 = s.getName();
    _builder.append(_name_1);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _generateInoSensorProc(final Sensor s, final Average th) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("final");
    String _name = s.getName();
    _builder.append(_name);
    _builder.append(" = temp");
    String _name_1 = s.getName();
    _builder.append(_name_1);
    _builder.append(" / count");
    String _name_2 = s.getName();
    _builder.append(_name_2);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _generateInoSensorRead(final Sound s) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("static bool read");
    String _name = s.getName();
    _builder.append(_name);
    _builder.append("( float *temp)");
    _builder.newLineIfNotEmpty();
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("static unsigned long measurement_timestamp = millis( );");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("/* Measure once every ");
    int _rate = s.getRate();
    _builder.append(_rate, "\t");
    _builder.append(" milliseconds. */");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("if( millis( ) - measurement_timestamp > ");
    int _rate_1 = s.getRate();
    _builder.append(_rate_1, "\t");
    _builder.append("ul )");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("temp = analogRead(");
    String _name_1 = s.getName();
    _builder.append(_name_1, "\t\t");
    _builder.append("AnalogPin)");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("return true");
    _builder.newLine();
    _builder.append("  \t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("  \t");
    _builder.append("return false");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  protected CharSequence _generateInoSensorRead(final Water_level s) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("static bool read");
    String _name = s.getName();
    _builder.append(_name);
    _builder.append("( float *temp)");
    _builder.newLineIfNotEmpty();
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("static unsigned long measurement_timestamp = millis( );");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("/* Measure once every ");
    int _rate = s.getRate();
    _builder.append(_rate, "\t");
    _builder.append(" milliseconds. */");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("if( millis( ) - measurement_timestamp > ");
    int _rate_1 = s.getRate();
    _builder.append(_rate_1, "\t");
    _builder.append("ul )");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("temp = analogRead(");
    String _name_1 = s.getName();
    _builder.append(_name_1, "\t\t");
    _builder.append("AnalogPin)");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("return true");
    _builder.newLine();
    _builder.append("  \t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("  \t");
    _builder.append("return false");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  protected CharSequence _generateInoSensorRead(final Sr04 s) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("static bool read");
    String _name = s.getName();
    _builder.append(_name);
    _builder.append("( float *temp)");
    _builder.newLineIfNotEmpty();
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("static unsigned long measurement_timestamp = millis( );");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("/* Measure once every four seconds. */");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("if( millis( ) - measurement_timestamp > ");
    int _rate = s.getRate();
    _builder.append(_rate, "\t");
    _builder.append("ul )");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("temp = sr04.Distance()");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return true");
    _builder.newLine();
    _builder.append("  \t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("  \t");
    _builder.append("return false");
    _builder.newLine();
    _builder.append("}\t");
    _builder.newLine();
    return _builder;
  }
  
  protected CharSequence _generateInoSensorVars(final Sensor s, final Threshold th) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("float temp");
    String _name = s.getName();
    _builder.append(_name);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("float final");
    String _name_1 = s.getName();
    _builder.append(_name_1);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("int min");
    String _name_2 = s.getName();
    _builder.append(_name_2);
    _builder.append(" = ");
    int _min = th.getMin();
    _builder.append(_min);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("int max");
    String _name_3 = s.getName();
    _builder.append(_name_3);
    _builder.append(" = ");
    int _max = th.getMax();
    _builder.append(_max);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _generateInoSensorVars(final Sensor s, final Average a) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("float temp");
    String _name = s.getName();
    _builder.append(_name);
    _builder.append(" = 0.0;");
    _builder.newLineIfNotEmpty();
    _builder.append("float final");
    String _name_1 = s.getName();
    _builder.append(_name_1);
    _builder.append(" = 0.0;");
    _builder.newLineIfNotEmpty();
    _builder.append("int count");
    String _name_2 = s.getName();
    _builder.append(_name_2);
    _builder.append(" = 0;");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _generateInoComsImports(final Edge e, final Edge __) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("\t");
    _builder.newLine();
    return _builder;
  }
  
  protected CharSequence _generateInoComsImports(final Edge e, final Nrf24l01 nrf) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("#include<RF24.h>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("// ce, csn pins");
    _builder.newLine();
    _builder.append("RF24 radio(9, 10);");
    _builder.newLine();
    _builder.append("uint8_t address = \"");
    String _name = e.getName();
    _builder.append(_name);
    _builder.append("\";");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _generateInoComsSetup(final Edge __) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("\t");
    _builder.newLine();
    return _builder;
  }
  
  protected CharSequence _generateInoComsSetup(final Nrf24l01 nrf) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("radio.begin();");
    _builder.newLine();
    _builder.append("radio.setPALevel(RF24_PA_LOW);");
    _builder.newLine();
    _builder.append("radio.openWritingPipe(address);");
    _builder.newLine();
    _builder.append("radio.setPayloadSize(32);");
    _builder.newLine();
    _builder.append("radio.powerUp();");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateReceiverFunction(final EObject f) {
    if (f instanceof Fog) {
      return _generateReceiverFunction((Fog)f);
    } else if (f instanceof Nrf24l01) {
      return _generateReceiverFunction((Nrf24l01)f);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(f).toString());
    }
  }
  
  public CharSequence generateInoSensorImports(final Sensor s) {
    if (s instanceof Sound) {
      return _generateInoSensorImports((Sound)s);
    } else if (s instanceof Sr04) {
      return _generateInoSensorImports((Sr04)s);
    } else if (s instanceof Water_level) {
      return _generateInoSensorImports((Water_level)s);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(s).toString());
    }
  }
  
  public CharSequence generateInoSensorProc(final Sensor s, final PreProcessor th) {
    if (th instanceof Average) {
      return _generateInoSensorProc(s, (Average)th);
    } else if (th instanceof Threshold) {
      return _generateInoSensorProc(s, (Threshold)th);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(s, th).toString());
    }
  }
  
  public CharSequence generateInoSensorRead(final Sensor s) {
    if (s instanceof Sound) {
      return _generateInoSensorRead((Sound)s);
    } else if (s instanceof Sr04) {
      return _generateInoSensorRead((Sr04)s);
    } else if (s instanceof Water_level) {
      return _generateInoSensorRead((Water_level)s);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(s).toString());
    }
  }
  
  public CharSequence generateInoSensorVars(final Sensor s, final PreProcessor a) {
    if (a instanceof Average) {
      return _generateInoSensorVars(s, (Average)a);
    } else if (a instanceof Threshold) {
      return _generateInoSensorVars(s, (Threshold)a);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(s, a).toString());
    }
  }
  
  public CharSequence generateInoComsImports(final Edge e, final EObject __) {
    if (__ instanceof Edge) {
      return _generateInoComsImports(e, (Edge)__);
    } else if (__ instanceof Nrf24l01) {
      return _generateInoComsImports(e, (Nrf24l01)__);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(e, __).toString());
    }
  }
  
  public CharSequence generateInoComsSetup(final EObject __) {
    if (__ instanceof Edge) {
      return _generateInoComsSetup((Edge)__);
    } else if (__ instanceof Nrf24l01) {
      return _generateInoComsSetup((Nrf24l01)__);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(__).toString());
    }
  }
}
