/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.sensorhub.ui.internal.SensorhubActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SensorHubExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SensorhubActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SensorhubActivator activator = SensorhubActivator.getInstance();
		return activator != null ? activator.getInjector(SensorhubActivator.ORG_XTEXT_EXAMPLE_MYDSL_SENSORHUB) : null;
	}

}
