/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SensorHubUiModule extends AbstractSensorHubUiModule {

	public SensorHubUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
