/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.sensorhub.ui.internal.SensorhubActivator;

public class SensorHubUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SensorhubActivator.getInstance().getInjector("org.xtext.example.mydsl.SensorHub");
	}

}
