/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.sensorHub;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Edge</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.sensorHub.Edge#getDevice <em>Device</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.sensorHub.SensorHubPackage#getEdge()
 * @model
 * @generated
 */
public interface Edge extends Device
{
  /**
   * Returns the value of the '<em><b>Device</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Device</em>' containment reference.
   * @see #setDevice(Arduino)
   * @see org.xtext.example.mydsl.sensorHub.SensorHubPackage#getEdge_Device()
   * @model containment="true"
   * @generated
   */
  Arduino getDevice();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sensorHub.Edge#getDevice <em>Device</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Device</em>' containment reference.
   * @see #getDevice()
   * @generated
   */
  void setDevice(Arduino value);

} // Edge
