/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.sensorHub;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fog</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.sensorHub.Fog#getComs <em>Coms</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.sensorHub.Fog#getDevice <em>Device</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.sensorHub.Fog#getEdgeDevices <em>Edge Devices</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.sensorHub.SensorHubPackage#getFog()
 * @model
 * @generated
 */
public interface Fog extends Device
{
  /**
   * Returns the value of the '<em><b>Coms</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Coms</em>' containment reference.
   * @see #setComs(Com)
   * @see org.xtext.example.mydsl.sensorHub.SensorHubPackage#getFog_Coms()
   * @model containment="true"
   * @generated
   */
  Com getComs();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sensorHub.Fog#getComs <em>Coms</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Coms</em>' containment reference.
   * @see #getComs()
   * @generated
   */
  void setComs(Com value);

  /**
   * Returns the value of the '<em><b>Device</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Device</em>' containment reference.
   * @see #setDevice(RaspPi)
   * @see org.xtext.example.mydsl.sensorHub.SensorHubPackage#getFog_Device()
   * @model containment="true"
   * @generated
   */
  RaspPi getDevice();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.sensorHub.Fog#getDevice <em>Device</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Device</em>' containment reference.
   * @see #getDevice()
   * @generated
   */
  void setDevice(RaspPi value);

  /**
   * Returns the value of the '<em><b>Edge Devices</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.sensorHub.Edge}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Edge Devices</em>' containment reference list.
   * @see org.xtext.example.mydsl.sensorHub.SensorHubPackage#getFog_EdgeDevices()
   * @model containment="true"
   * @generated
   */
  EList<Edge> getEdgeDevices();

} // Fog
