/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.sensorHub;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pre Processor</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.sensorHub.SensorHubPackage#getPreProcessor()
 * @model
 * @generated
 */
public interface PreProcessor extends EObject
{
} // PreProcessor
