/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.sensorHub;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rasp Pi</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.sensorHub.RaspPi#getStorage <em>Storage</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.sensorHub.RaspPi#getVisualization <em>Visualization</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.sensorHub.SensorHubPackage#getRaspPi()
 * @model
 * @generated
 */
public interface RaspPi extends EObject
{
  /**
   * Returns the value of the '<em><b>Storage</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.sensorHub.Storage}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Storage</em>' containment reference list.
   * @see org.xtext.example.mydsl.sensorHub.SensorHubPackage#getRaspPi_Storage()
   * @model containment="true"
   * @generated
   */
  EList<Storage> getStorage();

  /**
   * Returns the value of the '<em><b>Visualization</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.sensorHub.Visualizer}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visualization</em>' containment reference list.
   * @see org.xtext.example.mydsl.sensorHub.SensorHubPackage#getRaspPi_Visualization()
   * @model containment="true"
   * @generated
   */
  EList<Visualizer> getVisualization();

} // RaspPi
