/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.sensorHub;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.sensorHub.SensorHubFactory
 * @model kind="package"
 * @generated
 */
public interface SensorHubPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "sensorHub";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/SensorHub";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "sensorHub";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SensorHubPackage eINSTANCE = org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sensorHub.impl.SensorSystemImpl <em>Sensor System</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sensorHub.impl.SensorSystemImpl
   * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getSensorSystem()
   * @generated
   */
  int SENSOR_SYSTEM = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_SYSTEM__NAME = 0;

  /**
   * The feature id for the '<em><b>Devices</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_SYSTEM__DEVICES = 1;

  /**
   * The number of structural features of the '<em>Sensor System</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_SYSTEM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sensorHub.impl.DeviceImpl <em>Device</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sensorHub.impl.DeviceImpl
   * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getDevice()
   * @generated
   */
  int DEVICE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE__NAME = 0;

  /**
   * The number of structural features of the '<em>Device</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sensorHub.impl.FogImpl <em>Fog</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sensorHub.impl.FogImpl
   * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getFog()
   * @generated
   */
  int FOG = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOG__NAME = DEVICE__NAME;

  /**
   * The feature id for the '<em><b>Coms</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOG__COMS = DEVICE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Device</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOG__DEVICE = DEVICE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Edge Devices</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOG__EDGE_DEVICES = DEVICE_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Fog</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOG_FEATURE_COUNT = DEVICE_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sensorHub.impl.RaspPiImpl <em>Rasp Pi</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sensorHub.impl.RaspPiImpl
   * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getRaspPi()
   * @generated
   */
  int RASP_PI = 3;

  /**
   * The feature id for the '<em><b>Storage</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RASP_PI__STORAGE = 0;

  /**
   * The feature id for the '<em><b>Visualization</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RASP_PI__VISUALIZATION = 1;

  /**
   * The number of structural features of the '<em>Rasp Pi</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RASP_PI_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sensorHub.impl.StorageImpl <em>Storage</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sensorHub.impl.StorageImpl
   * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getStorage()
   * @generated
   */
  int STORAGE = 4;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE__TYPE = 0;

  /**
   * The number of structural features of the '<em>Storage</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sensorHub.impl.VisualizerImpl <em>Visualizer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sensorHub.impl.VisualizerImpl
   * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getVisualizer()
   * @generated
   */
  int VISUALIZER = 5;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VISUALIZER__TYPE = 0;

  /**
   * The number of structural features of the '<em>Visualizer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VISUALIZER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sensorHub.impl.EdgeImpl <em>Edge</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sensorHub.impl.EdgeImpl
   * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getEdge()
   * @generated
   */
  int EDGE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDGE__NAME = DEVICE__NAME;

  /**
   * The feature id for the '<em><b>Device</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDGE__DEVICE = DEVICE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Edge</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDGE_FEATURE_COUNT = DEVICE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sensorHub.impl.ArduinoImpl <em>Arduino</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sensorHub.impl.ArduinoImpl
   * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getArduino()
   * @generated
   */
  int ARDUINO = 7;

  /**
   * The feature id for the '<em><b>Rate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARDUINO__RATE = 0;

  /**
   * The feature id for the '<em><b>Sensors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARDUINO__SENSORS = 1;

  /**
   * The number of structural features of the '<em>Arduino</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARDUINO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sensorHub.impl.ComImpl <em>Com</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sensorHub.impl.ComImpl
   * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getCom()
   * @generated
   */
  int COM = 8;

  /**
   * The number of structural features of the '<em>Com</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COM_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sensorHub.impl.Nrf24l01Impl <em>Nrf24l01</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sensorHub.impl.Nrf24l01Impl
   * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getNrf24l01()
   * @generated
   */
  int NRF24L01 = 9;

  /**
   * The feature id for the '<em><b>Timeout</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NRF24L01__TIMEOUT = COM_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Nrf24l01</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NRF24L01_FEATURE_COUNT = COM_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sensorHub.impl.SensorImpl <em>Sensor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sensorHub.impl.SensorImpl
   * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getSensor()
   * @generated
   */
  int SENSOR = 10;

  /**
   * The feature id for the '<em><b>Rate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__RATE = 0;

  /**
   * The feature id for the '<em><b>Preprocessor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__PREPROCESSOR = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__NAME = 2;

  /**
   * The number of structural features of the '<em>Sensor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sensorHub.impl.Water_levelImpl <em>Water level</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sensorHub.impl.Water_levelImpl
   * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getWater_level()
   * @generated
   */
  int WATER_LEVEL = 11;

  /**
   * The feature id for the '<em><b>Rate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WATER_LEVEL__RATE = SENSOR__RATE;

  /**
   * The feature id for the '<em><b>Preprocessor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WATER_LEVEL__PREPROCESSOR = SENSOR__PREPROCESSOR;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WATER_LEVEL__NAME = SENSOR__NAME;

  /**
   * The number of structural features of the '<em>Water level</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WATER_LEVEL_FEATURE_COUNT = SENSOR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sensorHub.impl.Sr04Impl <em>Sr04</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sensorHub.impl.Sr04Impl
   * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getSr04()
   * @generated
   */
  int SR04 = 12;

  /**
   * The feature id for the '<em><b>Rate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SR04__RATE = SENSOR__RATE;

  /**
   * The feature id for the '<em><b>Preprocessor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SR04__PREPROCESSOR = SENSOR__PREPROCESSOR;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SR04__NAME = SENSOR__NAME;

  /**
   * The number of structural features of the '<em>Sr04</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SR04_FEATURE_COUNT = SENSOR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sensorHub.impl.SoundImpl <em>Sound</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sensorHub.impl.SoundImpl
   * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getSound()
   * @generated
   */
  int SOUND = 13;

  /**
   * The feature id for the '<em><b>Rate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOUND__RATE = SENSOR__RATE;

  /**
   * The feature id for the '<em><b>Preprocessor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOUND__PREPROCESSOR = SENSOR__PREPROCESSOR;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOUND__NAME = SENSOR__NAME;

  /**
   * The number of structural features of the '<em>Sound</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOUND_FEATURE_COUNT = SENSOR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sensorHub.impl.PreProcessorImpl <em>Pre Processor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sensorHub.impl.PreProcessorImpl
   * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getPreProcessor()
   * @generated
   */
  int PRE_PROCESSOR = 14;

  /**
   * The number of structural features of the '<em>Pre Processor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRE_PROCESSOR_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sensorHub.impl.AverageImpl <em>Average</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sensorHub.impl.AverageImpl
   * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getAverage()
   * @generated
   */
  int AVERAGE = 15;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AVERAGE__VALUE = PRE_PROCESSOR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Average</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AVERAGE_FEATURE_COUNT = PRE_PROCESSOR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.sensorHub.impl.ThresholdImpl <em>Threshold</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.sensorHub.impl.ThresholdImpl
   * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getThreshold()
   * @generated
   */
  int THRESHOLD = 16;

  /**
   * The feature id for the '<em><b>Min</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THRESHOLD__MIN = PRE_PROCESSOR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Max</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THRESHOLD__MAX = PRE_PROCESSOR_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Threshold</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THRESHOLD_FEATURE_COUNT = PRE_PROCESSOR_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sensorHub.SensorSystem <em>Sensor System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor System</em>'.
   * @see org.xtext.example.mydsl.sensorHub.SensorSystem
   * @generated
   */
  EClass getSensorSystem();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.sensorHub.SensorSystem#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.sensorHub.SensorSystem#getName()
   * @see #getSensorSystem()
   * @generated
   */
  EAttribute getSensorSystem_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.sensorHub.SensorSystem#getDevices <em>Devices</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Devices</em>'.
   * @see org.xtext.example.mydsl.sensorHub.SensorSystem#getDevices()
   * @see #getSensorSystem()
   * @generated
   */
  EReference getSensorSystem_Devices();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sensorHub.Device <em>Device</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Device</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Device
   * @generated
   */
  EClass getDevice();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.sensorHub.Device#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Device#getName()
   * @see #getDevice()
   * @generated
   */
  EAttribute getDevice_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sensorHub.Fog <em>Fog</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fog</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Fog
   * @generated
   */
  EClass getFog();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.sensorHub.Fog#getComs <em>Coms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Coms</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Fog#getComs()
   * @see #getFog()
   * @generated
   */
  EReference getFog_Coms();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.sensorHub.Fog#getDevice <em>Device</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Device</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Fog#getDevice()
   * @see #getFog()
   * @generated
   */
  EReference getFog_Device();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.sensorHub.Fog#getEdgeDevices <em>Edge Devices</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Edge Devices</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Fog#getEdgeDevices()
   * @see #getFog()
   * @generated
   */
  EReference getFog_EdgeDevices();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sensorHub.RaspPi <em>Rasp Pi</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rasp Pi</em>'.
   * @see org.xtext.example.mydsl.sensorHub.RaspPi
   * @generated
   */
  EClass getRaspPi();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.sensorHub.RaspPi#getStorage <em>Storage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Storage</em>'.
   * @see org.xtext.example.mydsl.sensorHub.RaspPi#getStorage()
   * @see #getRaspPi()
   * @generated
   */
  EReference getRaspPi_Storage();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.sensorHub.RaspPi#getVisualization <em>Visualization</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Visualization</em>'.
   * @see org.xtext.example.mydsl.sensorHub.RaspPi#getVisualization()
   * @see #getRaspPi()
   * @generated
   */
  EReference getRaspPi_Visualization();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sensorHub.Storage <em>Storage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Storage</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Storage
   * @generated
   */
  EClass getStorage();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.sensorHub.Storage#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Storage#getType()
   * @see #getStorage()
   * @generated
   */
  EAttribute getStorage_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sensorHub.Visualizer <em>Visualizer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Visualizer</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Visualizer
   * @generated
   */
  EClass getVisualizer();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.sensorHub.Visualizer#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Visualizer#getType()
   * @see #getVisualizer()
   * @generated
   */
  EAttribute getVisualizer_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sensorHub.Edge <em>Edge</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Edge</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Edge
   * @generated
   */
  EClass getEdge();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.sensorHub.Edge#getDevice <em>Device</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Device</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Edge#getDevice()
   * @see #getEdge()
   * @generated
   */
  EReference getEdge_Device();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sensorHub.Arduino <em>Arduino</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Arduino</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Arduino
   * @generated
   */
  EClass getArduino();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.sensorHub.Arduino#getRate <em>Rate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rate</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Arduino#getRate()
   * @see #getArduino()
   * @generated
   */
  EAttribute getArduino_Rate();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.sensorHub.Arduino#getSensors <em>Sensors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sensors</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Arduino#getSensors()
   * @see #getArduino()
   * @generated
   */
  EReference getArduino_Sensors();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sensorHub.Com <em>Com</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Com</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Com
   * @generated
   */
  EClass getCom();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sensorHub.Nrf24l01 <em>Nrf24l01</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nrf24l01</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Nrf24l01
   * @generated
   */
  EClass getNrf24l01();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.sensorHub.Nrf24l01#getTimeout <em>Timeout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Timeout</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Nrf24l01#getTimeout()
   * @see #getNrf24l01()
   * @generated
   */
  EAttribute getNrf24l01_Timeout();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sensorHub.Sensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Sensor
   * @generated
   */
  EClass getSensor();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.sensorHub.Sensor#getRate <em>Rate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rate</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Sensor#getRate()
   * @see #getSensor()
   * @generated
   */
  EAttribute getSensor_Rate();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.sensorHub.Sensor#getPreprocessor <em>Preprocessor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Preprocessor</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Sensor#getPreprocessor()
   * @see #getSensor()
   * @generated
   */
  EReference getSensor_Preprocessor();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.sensorHub.Sensor#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Sensor#getName()
   * @see #getSensor()
   * @generated
   */
  EAttribute getSensor_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sensorHub.Water_level <em>Water level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Water level</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Water_level
   * @generated
   */
  EClass getWater_level();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sensorHub.Sr04 <em>Sr04</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sr04</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Sr04
   * @generated
   */
  EClass getSr04();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sensorHub.Sound <em>Sound</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sound</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Sound
   * @generated
   */
  EClass getSound();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sensorHub.PreProcessor <em>Pre Processor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pre Processor</em>'.
   * @see org.xtext.example.mydsl.sensorHub.PreProcessor
   * @generated
   */
  EClass getPreProcessor();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sensorHub.Average <em>Average</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Average</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Average
   * @generated
   */
  EClass getAverage();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.sensorHub.Average#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Average#getValue()
   * @see #getAverage()
   * @generated
   */
  EAttribute getAverage_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.sensorHub.Threshold <em>Threshold</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Threshold</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Threshold
   * @generated
   */
  EClass getThreshold();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.sensorHub.Threshold#getMin <em>Min</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Min</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Threshold#getMin()
   * @see #getThreshold()
   * @generated
   */
  EAttribute getThreshold_Min();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.sensorHub.Threshold#getMax <em>Max</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max</em>'.
   * @see org.xtext.example.mydsl.sensorHub.Threshold#getMax()
   * @see #getThreshold()
   * @generated
   */
  EAttribute getThreshold_Max();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SensorHubFactory getSensorHubFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sensorHub.impl.SensorSystemImpl <em>Sensor System</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sensorHub.impl.SensorSystemImpl
     * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getSensorSystem()
     * @generated
     */
    EClass SENSOR_SYSTEM = eINSTANCE.getSensorSystem();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR_SYSTEM__NAME = eINSTANCE.getSensorSystem_Name();

    /**
     * The meta object literal for the '<em><b>Devices</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR_SYSTEM__DEVICES = eINSTANCE.getSensorSystem_Devices();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sensorHub.impl.DeviceImpl <em>Device</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sensorHub.impl.DeviceImpl
     * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getDevice()
     * @generated
     */
    EClass DEVICE = eINSTANCE.getDevice();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEVICE__NAME = eINSTANCE.getDevice_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sensorHub.impl.FogImpl <em>Fog</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sensorHub.impl.FogImpl
     * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getFog()
     * @generated
     */
    EClass FOG = eINSTANCE.getFog();

    /**
     * The meta object literal for the '<em><b>Coms</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOG__COMS = eINSTANCE.getFog_Coms();

    /**
     * The meta object literal for the '<em><b>Device</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOG__DEVICE = eINSTANCE.getFog_Device();

    /**
     * The meta object literal for the '<em><b>Edge Devices</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOG__EDGE_DEVICES = eINSTANCE.getFog_EdgeDevices();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sensorHub.impl.RaspPiImpl <em>Rasp Pi</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sensorHub.impl.RaspPiImpl
     * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getRaspPi()
     * @generated
     */
    EClass RASP_PI = eINSTANCE.getRaspPi();

    /**
     * The meta object literal for the '<em><b>Storage</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RASP_PI__STORAGE = eINSTANCE.getRaspPi_Storage();

    /**
     * The meta object literal for the '<em><b>Visualization</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RASP_PI__VISUALIZATION = eINSTANCE.getRaspPi_Visualization();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sensorHub.impl.StorageImpl <em>Storage</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sensorHub.impl.StorageImpl
     * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getStorage()
     * @generated
     */
    EClass STORAGE = eINSTANCE.getStorage();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORAGE__TYPE = eINSTANCE.getStorage_Type();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sensorHub.impl.VisualizerImpl <em>Visualizer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sensorHub.impl.VisualizerImpl
     * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getVisualizer()
     * @generated
     */
    EClass VISUALIZER = eINSTANCE.getVisualizer();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VISUALIZER__TYPE = eINSTANCE.getVisualizer_Type();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sensorHub.impl.EdgeImpl <em>Edge</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sensorHub.impl.EdgeImpl
     * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getEdge()
     * @generated
     */
    EClass EDGE = eINSTANCE.getEdge();

    /**
     * The meta object literal for the '<em><b>Device</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EDGE__DEVICE = eINSTANCE.getEdge_Device();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sensorHub.impl.ArduinoImpl <em>Arduino</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sensorHub.impl.ArduinoImpl
     * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getArduino()
     * @generated
     */
    EClass ARDUINO = eINSTANCE.getArduino();

    /**
     * The meta object literal for the '<em><b>Rate</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARDUINO__RATE = eINSTANCE.getArduino_Rate();

    /**
     * The meta object literal for the '<em><b>Sensors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARDUINO__SENSORS = eINSTANCE.getArduino_Sensors();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sensorHub.impl.ComImpl <em>Com</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sensorHub.impl.ComImpl
     * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getCom()
     * @generated
     */
    EClass COM = eINSTANCE.getCom();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sensorHub.impl.Nrf24l01Impl <em>Nrf24l01</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sensorHub.impl.Nrf24l01Impl
     * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getNrf24l01()
     * @generated
     */
    EClass NRF24L01 = eINSTANCE.getNrf24l01();

    /**
     * The meta object literal for the '<em><b>Timeout</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NRF24L01__TIMEOUT = eINSTANCE.getNrf24l01_Timeout();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sensorHub.impl.SensorImpl <em>Sensor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sensorHub.impl.SensorImpl
     * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getSensor()
     * @generated
     */
    EClass SENSOR = eINSTANCE.getSensor();

    /**
     * The meta object literal for the '<em><b>Rate</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR__RATE = eINSTANCE.getSensor_Rate();

    /**
     * The meta object literal for the '<em><b>Preprocessor</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR__PREPROCESSOR = eINSTANCE.getSensor_Preprocessor();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR__NAME = eINSTANCE.getSensor_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sensorHub.impl.Water_levelImpl <em>Water level</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sensorHub.impl.Water_levelImpl
     * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getWater_level()
     * @generated
     */
    EClass WATER_LEVEL = eINSTANCE.getWater_level();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sensorHub.impl.Sr04Impl <em>Sr04</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sensorHub.impl.Sr04Impl
     * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getSr04()
     * @generated
     */
    EClass SR04 = eINSTANCE.getSr04();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sensorHub.impl.SoundImpl <em>Sound</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sensorHub.impl.SoundImpl
     * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getSound()
     * @generated
     */
    EClass SOUND = eINSTANCE.getSound();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sensorHub.impl.PreProcessorImpl <em>Pre Processor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sensorHub.impl.PreProcessorImpl
     * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getPreProcessor()
     * @generated
     */
    EClass PRE_PROCESSOR = eINSTANCE.getPreProcessor();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sensorHub.impl.AverageImpl <em>Average</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sensorHub.impl.AverageImpl
     * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getAverage()
     * @generated
     */
    EClass AVERAGE = eINSTANCE.getAverage();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AVERAGE__VALUE = eINSTANCE.getAverage_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.sensorHub.impl.ThresholdImpl <em>Threshold</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.sensorHub.impl.ThresholdImpl
     * @see org.xtext.example.mydsl.sensorHub.impl.SensorHubPackageImpl#getThreshold()
     * @generated
     */
    EClass THRESHOLD = eINSTANCE.getThreshold();

    /**
     * The meta object literal for the '<em><b>Min</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute THRESHOLD__MIN = eINSTANCE.getThreshold_Min();

    /**
     * The meta object literal for the '<em><b>Max</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute THRESHOLD__MAX = eINSTANCE.getThreshold_Max();

  }

} //SensorHubPackage
