/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.sensorHub;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.sensorHub.SensorHubPackage
 * @generated
 */
public interface SensorHubFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SensorHubFactory eINSTANCE = org.xtext.example.mydsl.sensorHub.impl.SensorHubFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Sensor System</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sensor System</em>'.
   * @generated
   */
  SensorSystem createSensorSystem();

  /**
   * Returns a new object of class '<em>Device</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Device</em>'.
   * @generated
   */
  Device createDevice();

  /**
   * Returns a new object of class '<em>Fog</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fog</em>'.
   * @generated
   */
  Fog createFog();

  /**
   * Returns a new object of class '<em>Rasp Pi</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rasp Pi</em>'.
   * @generated
   */
  RaspPi createRaspPi();

  /**
   * Returns a new object of class '<em>Storage</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Storage</em>'.
   * @generated
   */
  Storage createStorage();

  /**
   * Returns a new object of class '<em>Visualizer</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Visualizer</em>'.
   * @generated
   */
  Visualizer createVisualizer();

  /**
   * Returns a new object of class '<em>Edge</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Edge</em>'.
   * @generated
   */
  Edge createEdge();

  /**
   * Returns a new object of class '<em>Arduino</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Arduino</em>'.
   * @generated
   */
  Arduino createArduino();

  /**
   * Returns a new object of class '<em>Com</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Com</em>'.
   * @generated
   */
  Com createCom();

  /**
   * Returns a new object of class '<em>Nrf24l01</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Nrf24l01</em>'.
   * @generated
   */
  Nrf24l01 createNrf24l01();

  /**
   * Returns a new object of class '<em>Sensor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sensor</em>'.
   * @generated
   */
  Sensor createSensor();

  /**
   * Returns a new object of class '<em>Water level</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Water level</em>'.
   * @generated
   */
  Water_level createWater_level();

  /**
   * Returns a new object of class '<em>Sr04</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sr04</em>'.
   * @generated
   */
  Sr04 createSr04();

  /**
   * Returns a new object of class '<em>Sound</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sound</em>'.
   * @generated
   */
  Sound createSound();

  /**
   * Returns a new object of class '<em>Pre Processor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pre Processor</em>'.
   * @generated
   */
  PreProcessor createPreProcessor();

  /**
   * Returns a new object of class '<em>Average</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Average</em>'.
   * @generated
   */
  Average createAverage();

  /**
   * Returns a new object of class '<em>Threshold</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Threshold</em>'.
   * @generated
   */
  Threshold createThreshold();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  SensorHubPackage getSensorHubPackage();

} //SensorHubFactory
