/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.sensorHub;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sound</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.sensorHub.SensorHubPackage#getSound()
 * @model
 * @generated
 */
public interface Sound extends Sensor
{
} // Sound
