/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.sensorHub;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sr04</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.sensorHub.SensorHubPackage#getSr04()
 * @model
 * @generated
 */
public interface Sr04 extends Sensor
{
} // Sr04
