/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.sensorHub;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Water level</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.sensorHub.SensorHubPackage#getWater_level()
 * @model
 * @generated
 */
public interface Water_level extends Sensor
{
} // Water_level
