/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.sensorHub.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.sensorHub.PreProcessor;
import org.xtext.example.mydsl.sensorHub.SensorHubPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Pre Processor</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PreProcessorImpl extends MinimalEObjectImpl.Container implements PreProcessor
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PreProcessorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SensorHubPackage.Literals.PRE_PROCESSOR;
  }

} //PreProcessorImpl
