/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.sensorHub.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.sensorHub.SensorHubPackage;
import org.xtext.example.mydsl.sensorHub.Sr04;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sr04</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class Sr04Impl extends SensorImpl implements Sr04
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Sr04Impl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SensorHubPackage.Literals.SR04;
  }

} //Sr04Impl
