/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.sensorHub.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.sensorHub.SensorHubPackage;
import org.xtext.example.mydsl.sensorHub.Water_level;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Water level</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class Water_levelImpl extends SensorImpl implements Water_level
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Water_levelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SensorHubPackage.Literals.WATER_LEVEL;
  }

} //Water_levelImpl
